$:.unshift './app'

require 'helpers/move_validator'
require 'controllers/game_loop'
require 'views/view'
require 'views/counter'
require 'models/tic_tac_toe'
require 'models/player'
require 'models/human'
require 'models/ai'
require 'models/random_ai'
